In [1]:
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    print sess.run(x)
    
writer.close()
#在终端当前目录下输入 $ tensorboard --logdir="./graphs"
#浏览器打开http://localhost:6006/
#选择graph可以看到这个结构的图

5


In [2]:
import tensorflow as tf
a = tf.constant([2,3],name="a")
b = tf.constant([3,6],name="b")
x = tf.add(a,b,name="add")
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    print sess.run(x)
    
writer.close()
#在终端当前目录下输入 $ tensorboard --logdir="./graphs"
#浏览器打开http://localhost:6006/
#选择graph可以看到这个结构的图
#可以看到三个点被命名了

[5 9]


接下来学习恒量 tf.constant

In [3]:
#constant可以被是标量（scalar）或者张量（tensor）
a = tf.constant([2,2],name="vector")
b = tf.constant([[1,2],[3,4]],name="matrix")

In [4]:
#创建全0的张量
a = tf.zeros([2,3],tf.int32)
with tf.Session() as sess:
    print sess.run(a)

[[0 0 0]
 [0 0 0]]


In [5]:
#创建全1的张量
a = tf.ones([2,3],tf.int32)
with tf.Session() as sess:
    print sess.run(a)

[[1 1 1]
 [1 1 1]]


In [6]:
#按照某个tensor的形状创建一个全1或者全某个数的tensor
b = tf.ones_like(a)
c = tf.zeros_like(a)
with tf.Session() as sess:
    print sess.run(b)
    print sess.run(c)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [7]:
#创建一个全是某数的tensor
a = tf.fill([4,5],8)
with tf.Session() as sess:
    print sess.run(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [8]:
#创建连续的衡量
#tf.linspace(start, stop, num, name=None)
a = tf.linspace(10.0, 13.0, 4, name="linspace")
with tf.Session() as sess:
    print sess.run(a)

[ 10.  11.  12.  13.]


In [9]:
#创建一个增量是delta的串衡量
#tf.range(start,limit=None,delta=1,dtype=None,name='range')
a = tf.range(3,18,3)
b = tf.range(3,1,-.4)
c = tf.range(8)
with tf.Session() as sess:
    print sess.run(a)
    print sess.run(b)
    print sess.run(c)

[ 3  6  9 12 15]
[ 3.          2.5999999   2.19999981  1.79999983  1.39999986]
[0 1 2 3 4 5 6 7]


In [ ]:
# 这个是在区分numpy与tensorflow中的不同
# for _ in np.linspace(0, 10, 4): # OK
# for _ in tf.linspace(0, 10, 4): # TypeError("'Tensor' object is not iterable.")
# for _ in range(4): # OK
# for _ in tf.range(4): # TypeError("'Tensor' object is not iterable.")

In [ ]:
# 以下函数生成衡量
# tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
# tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None,name=None)
# tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None,name=None)
# tf.random_shuffle(value, seed=None, name=None)
# tf.random_crop(value, size, seed=None, name=None)
# tf.multinomial(logits, num_samples, seed=None, name=None)
# tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)

In [ ]:
# 以下为数学计算用的
# a = tf.constant([3, 6])
# b = tf.constant([2, 2])
# tf.add(a, b) # >> [5 8]
# tf.add_n([a, b, b]) # >> [7 10]. Equivalent to a + b + b
# tf.mul(a, b) # >> [6 12] because mul is element wise
# tf.matmul(a, b) # >> ValueError
# tf.matmul(tf.reshape(a, shape=[1, 2]), tf.reshape(b, shape=[2, 1])) # >> [[18]]
# tf.div(a, b) # >> [1 3]
# tf.mod(a, b) # >> [1 0]

In [ ]:
# 参照Python类型生成

# t_0 = 19 # Treated as a 0-d tensor, or "scalar"
# tf.zeros_like(t_0) # ==> 0
# tf.ones_like(t_0) # ==> 1
# t_1 = [b"apple", b"peach", b"grape"] # treated as a 1-d tensor, or "vector"
# tf.zeros_like(t_1) # ==> ['' '' '']
# tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.
# t_2 = [[True, False, False],
#  [False, False, True],
#  [False, True, False]] # treated as a 2-d tensor, or "matrix"
# tf.zeros_like(t_2) # ==> 2x2 tensor, all elements are False
# tf.ones_like(t_2) # ==> 2x2 tensor, all elements are True

In [ ]:
# 变量 variable
# 使用变量前，要初始化
# init = tf.global_variables_initializer()
# with tf.Session() as sess:
#     tf.run(init)

# 也可以指定初始化
# init_ab = tf.variables_initializer([a, b], name="init_ab")
# with tf.Session() as sess:
#     tf.run(init_ab)

In [10]:
# 给变量赋值操作需要卸载sess.run里执行

W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()
    
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(assign_op)
    print W.eval() 
# assign()里面包含了初始化

10
100


In [11]:
# InteractiveSession
# 使用这个，在调用run()和eval()的时候不用调用session
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

30.0


In [ ]:
# 节点依赖，或者执行顺序
# your graph g have 5 ops: a, b, c, d, e
# with g.control_dependencies([a, b, c]):
#  #`d` and `e` will only run after `a`, `b`, and `c` have executed.
#  d = ...
#  e = …

In [12]:
# 占位符（placeholder） 

# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)
# If we try to fetch c, we will run into error.
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./my_graph', sess.graph)
    print(sess.run(c, {a: [1, 2, 3]}))
    

[ 6.  7.  8.]
